INSERT INTO INTEREST VALUES(1,'fizyka');
INSERT INTO INTEREST VALUES(2,'chemia');
INSERT INTO INTEREST VALUES(3,'matematyka');

INSERT INTO STUDENT VALUES(1,'Ziemek','RT');
INSERT INTO STUDENT VALUES(2,'Maciuś','MT');
INSERT INTO STUDENT VALUES(3,'Jagienka','MT');

